"""
pseofactory.edge: Centralized Edge Infrastructure & Standards.
Provides centralized Cloudflare Pages edge headers builder,
host configuration hygiene auditing, and edge header validation.
Zero em-dashes. Zero en-dashes.
"""

import json
from pathlib import Path
import re
from typing import Any, Dict, List, Optional, Union


class EdgeConfigStandards:
    """Standardized edge caching directives and machine content types."""

    STATIC_CACHE: str = "public, max-age=31536000, immutable"
    HTML_MACHINE_CACHE: str = "public, max-age=3600, s-maxage=86400, stale-while-revalidate=604800"
    ERROR_CACHE: str = "no-store"
    SECURITY_HEADERS: Dict[str, str] = {
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "SAMEORIGIN",
        "Referrer-Policy": "strict-origin-when-cross-origin",
    }
    MACHINE_CONTENT_TYPES: Dict[str, str] = {
        ".xml": "application/xml; charset=utf-8",
        ".txt": "text/plain; charset=utf-8",
        ".json": "application/json; charset=utf-8",
    }


def build_edge_headers(
    canonical_base: str,
    routes: Optional[List[str]] = None,
    machine_endpoints: Optional[List[str]] = None,
    static_patterns: Optional[List[str]] = None,
    custom_headers: Optional[Dict[str, List[str]]] = None,
) -> str:
    """
    Builds standard Cloudflare Pages dist/_headers syntax.
    Enforces immutable static asset caching, edge s-maxage and stale-while-revalidate
    on root HTML, RFC 5988 canonical Link headers, and UTF-8 machine content types.
    Strictly forbids noindex or nosnippet on public routes.
    """
    base = canonical_base.rstrip("/")
    lines: List[str] = [
        "# Cloudflare Pages Edge Headers generated by pseofactory.edge",
    ]

    # 1. Static asset cache policies
    patterns = static_patterns if static_patterns is not None else [
        "/static/css/*",
        "/static/js/*",
        "/static/*",
        "/css/*",
        "/js/*",
        "/assets/*",
    ]
    for pattern in patterns:
        lines.append(pattern)
        lines.append(f"  Cache-Control: {EdgeConfigStandards.STATIC_CACHE}")
        lines.append("")

    # 2. Root HTML fallback and security headers
    lines.append("/*")
    lines.append(f"  Cache-Control: {EdgeConfigStandards.HTML_MACHINE_CACHE}")
    for sec_header, sec_val in EdgeConfigStandards.SECURITY_HEADERS.items():
        lines.append(f"  {sec_header}: {sec_val}")
    lines.append("")

    # 3. 404 Error page cache policy
    lines.append("/404.html")
    lines.append(f"  Cache-Control: {EdgeConfigStandards.ERROR_CACHE}")
    lines.append("")

    # 4. Machine endpoints (RFC 5988 canonical link and UTF-8 charset content-type)
    endpoints = machine_endpoints if machine_endpoints is not None else [
        "/feed.xml",
        "/llms.txt",
        "/llms-full.txt",
        "/sitemap.xml",
        "/sitemap-hubs.xml",
        "/sitemap-leaves.xml",
    ]
    for ep in endpoints:
        path = ep if ep.startswith("/") else f"/{ep}"
        lines.append(path)
        lines.append(f'  Link: <{base}{path}>; rel="canonical"')
        ext = Path(path).suffix.lower()
        if ext in EdgeConfigStandards.MACHINE_CONTENT_TYPES:
            ct = EdgeConfigStandards.MACHINE_CONTENT_TYPES[ext]
            lines.append(f"  Content-Type: {ct}")
        lines.append("")

    # 5. Public HTML routes (RFC 5988 canonical link)
    if routes:
        for r in routes:
            path = r if r.startswith("/") else f"/{r}"
            lines.append(path)
            lines.append(f'  Link: <{base}{path}>; rel="canonical"')
            lines.append("")

    # 6. Custom headers
    if custom_headers:
        for route_key, header_list in custom_headers.items():
            path = route_key if route_key.startswith("/") else f"/{route_key}"
            lines.append(path)
            for h in header_list:
                lines.append(f"  {h}")
            lines.append("")

    content = "\n".join(lines).rstrip() + "\n"

    # Validate against snippet policy if contracts available
    try:
        from pseofactory.contracts import assert_headers_snippet_policy
        assert_headers_snippet_policy(content, context="build_edge_headers")
    except ImportError:
        pass

    return content


class HostHygieneAuditor:
    """Audits root deployment configuration files for crawler hygiene."""

    @classmethod
    def audit_repo_host_configs(cls, repo_path: Union[str, Path]) -> Dict[str, Any]:
        """
        Audits firebase.json, wrangler.toml, etc., in target repository.
        Catches blanket noindex directives and verifies cache retention policies.
        """
        repo = Path(repo_path)
        issues: List[str] = []
        configs_checked: List[str] = []

        if not repo.exists() or not repo.is_dir():
            return {
                "status": "FAIL",
                "repo_path": str(repo),
                "configs_checked": [],
                "violations_count": 1,
                "issues": [f"Repository path does not exist: {repo}"],
            }

        # 1. Audit firebase.json
        firebase_file = repo / "firebase.json"
        if firebase_file.is_file():
            configs_checked.append("firebase.json")
            try:
                data = json.loads(firebase_file.read_text(encoding="utf-8"))
                headers_rules = data.get("hosting", {}).get("headers", [])
                has_edge_cache = False

                for rule in headers_rules:
                    src = (rule.get("source") or "").strip()
                    for h in rule.get("headers", []):
                        k = (h.get("key") or "").strip().lower()
                        v = (h.get("value") or "").strip().lower()

                        # Detect blanket noindex / nofollow / noarchive on public wildcards
                        if src in ("**", "/*", "*") and k == "x-robots-tag":
                            if any(d in v for d in ["noindex", "nofollow", "noarchive"]):
                                issues.append(
                                    f"firebase.json contains lethal X-Robots-Tag directive '{v}' on wildcard '{src}'"
                                )

                        # Detect edge caching directives
                        if k == "cache-control":
                            if "s-maxage=86400" in v and "stale-while-revalidate=604800" in v:
                                has_edge_cache = True

                if not has_edge_cache:
                    issues.append(
                        "firebase.json missing s-maxage=86400 and stale-while-revalidate=604800 in cache headers"
                    )
            except Exception as e:
                issues.append(f"Failed to parse firebase.json: {e}")

        # 2. Audit wrangler.toml
        wrangler_file = repo / "wrangler.toml"
        if wrangler_file.is_file():
            configs_checked.append("wrangler.toml")
            try:
                wrangler_content = wrangler_file.read_text(encoding="utf-8")
                if "noindex" in wrangler_content.lower():
                    issues.append("wrangler.toml contains potential noindex directive")
            except Exception as e:
                issues.append(f"Failed to read wrangler.toml: {e}")

        return {
            "status": "PASS" if not issues else "FAIL",
            "repo_path": str(repo),
            "configs_checked": configs_checked,
            "violations_count": len(issues),
            "issues": issues,
        }

    def audit(self, repo_path: Union[str, Path]) -> Dict[str, Any]:
        """Instance method delegating to classmethod."""
        return self.audit_repo_host_configs(repo_path)


def validate_edge_headers_file(headers_path: Union[str, Path]) -> Dict[str, Any]:
    """
    Validates compiled dist/_headers file.
    Asserts presence of s-maxage, stale-while-revalidate, immutable static assets,
    RFC 5988 canonical links on machine endpoints, and zero crawler barriers.
    """
    hp = Path(headers_path)
    issues: List[str] = []

    if not hp.is_file():
        return {
            "status": "FAIL",
            "headers_path": str(hp),
            "violations_count": 1,
            "issues": [f"Headers file not found: {hp}"],
        }

    try:
        content = hp.read_text(encoding="utf-8")
    except Exception as e:
        return {
            "status": "FAIL",
            "headers_path": str(hp),
            "violations_count": 1,
            "issues": [f"Failed to read headers file: {e}"],
        }

    # Contract verification
    try:
        from pseofactory.contracts import assert_headers_snippet_policy
        assert_headers_snippet_policy(content, context=str(hp))
    except Exception as e:
        issues.append(f"Snippet policy violation: {e}")

    # Parse route headers
    route_headers: Dict[str, Dict[str, str]] = {}
    current_route = ""
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if not raw_line.startswith(" ") and not raw_line.startswith("\t"):
            current_route = line
            if current_route not in route_headers:
                route_headers[current_route] = {}
        else:
            if ":" in line and current_route:
                k, v = line.split(":", 1)
                route_headers[current_route][k.strip().lower()] = v.strip()

    # 1. Check root route /* cache control
    root_hdrs = route_headers.get("/*", {})
    root_cc = root_hdrs.get("cache-control", "").lower()
    if not root_cc:
        issues.append("Missing Cache-Control header for root route '/*'")
    else:
        if "s-maxage=86400" not in root_cc:
            issues.append("Root route '/* missing s-maxage=86400 in Cache-Control")
        if "stale-while-revalidate=604800" not in root_cc:
            issues.append("Root route '/* missing stale-while-revalidate=604800 in Cache-Control")

    # 2. Check static assets have immutable
    static_routes = [r for r in route_headers if any(pat in r for pat in ["/static", "/css", "/js", "/assets"])]
    for sr in static_routes:
        cc = route_headers[sr].get("cache-control", "").lower()
        if "immutable" not in cc:
            issues.append(f"Static pattern '{sr}' missing 'immutable' directive in Cache-Control")

    # 3. Check machine endpoints declare RFC 5988 canonical link and UTF-8 charset
    machine_exts = (".xml", ".txt", ".json")
    for r, hdrs in route_headers.items():
        if any(r.endswith(ext) for ext in machine_exts):
            link = hdrs.get("link", "")
            if 'rel="canonical"' not in link and "rel='canonical'" not in link:
                issues.append(f"Machine endpoint '{r}' missing RFC 5988 canonical Link header")
            ct = hdrs.get("content-type", "")
            if "charset=utf-8" not in ct.lower():
                issues.append(f"Machine endpoint '{r}' missing UTF-8 charset in Content-Type")

    # 4. Check for lethal crawler barriers on public routes
    for r, hdrs in route_headers.items():
        if r.startswith(("/signal", "/staging", "/test")):
            continue
        x_robots = hdrs.get("x-robots-tag", "").lower()
        if "noindex" in x_robots:
            issues.append(f"Public route '{r}' has lethal noindex directive")
        if "nosnippet" in x_robots:
            issues.append(f"Public route '{r}' has lethal nosnippet directive")
        if "max-snippet:0" in x_robots:
            issues.append(f"Public route '{r}' has lethal max-snippet:0 directive")

    return {
        "status": "PASS" if not issues else "FAIL",
        "headers_path": str(hp),
        "violations_count": len(issues),
        "issues": issues,
    }
